baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
title = "Haoming Bai"
theme = "blowfish"
relativeURLs = true
canonifyURLs = false
enableRobotsTXT = true
hasCJKLanguage = true

[pagination]
  pagerSize = 10

taxonomies = { tag = "tags" }

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
  [markup.goldmark.renderer]
    unsafe = true

[params]
  colorScheme = "ocean"
  defaultAppearance = "system"
  autoSwitchAppearance = true
  showReadingTime = true
  enableSearch = true
  customCSS = ["css/custom.css"]

  [params.homepage]
    layout = "page"
    showRecent = true
    showRecentItems = 5
    showMoreLink = true
    showMoreLinkDest = "/posts/"

  [params.article]
    showTableOfContents = true
    showTaxonomies = true
    showAuthor = false
    showAuthorBottom = false
    showAuthorsBadges = false

[params.author]
  name = "Haoming Bai"
  image = "avatar.png"
  headline = "工程师 / 创作者"
  bio = "专注于 Web 与平台工程"

[params.comments]
  enabled = false

[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    pageRef = "/posts/"
    weight = 20
  [[menu.main]]
    name = "About"
    pageRef = "/about/"
    weight = 30
